"""adiciona movimentacoes_synced_at em processos

Revision ID: 203b0274458c
Revises: a46336bed1eb
Create Date: 2026-08-22 22:11:35.792089

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '203b0274458c'
down_revision: Union[str, None] = 'a46336bed1eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('processos', sa.Column('movimentacoes_synced_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('processos', 'movimentacoes_synced_at')
    # ### end Alembic commands ###
