"""constraints de unicidade por advogado e hash de movimentacao

Revision ID: 34c3ebb0c7e4
Revises: 0b7c41e5d9a3
Create Date: 2026-08-05 14:07:59.270413

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '34c3ebb0c7e4'
down_revision: Union[str, None] = '0b7c41e5d9a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_audiencias_id_esaj'), 'audiencias', type_='unique')
    op.create_unique_constraint(op.f('uq_audiencias_user_id_id_esaj'), 'audiencias', ['user_id', 'id_esaj'])
    op.drop_constraint(op.f('uq_intimacoes_id_esaj'), 'intimacoes', type_='unique')
    op.create_unique_constraint(op.f('uq_intimacoes_user_id_id_esaj'), 'intimacoes', ['user_id', 'id_esaj'])
    op.add_column('movimentacoes', sa.Column('descricao_hash', sa.String(length=64), nullable=False))
    op.drop_constraint(op.f('uq_movimentacoes_processo_id_data_movimentacao_descricao'), 'movimentacoes', type_='unique')
    op.create_unique_constraint(op.f('uq_movimentacoes_processo_id_data_movimentacao_descricao_hash'), 'movimentacoes', ['processo_id', 'data_movimentacao', 'descricao_hash'])
    op.create_unique_constraint(op.f('uq_tribunal_credentials_user_id_tribunal'), 'tribunal_credentials', ['user_id', 'tribunal'])
    op.create_index('ix_tribunal_sessions_status_proximo_retry', 'tribunal_sessions', ['status', 'proximo_retry'], unique=False)
    op.create_unique_constraint(op.f('uq_tribunal_sessions_user_id_tribunal'), 'tribunal_sessions', ['user_id', 'tribunal'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_tribunal_sessions_user_id_tribunal'), 'tribunal_sessions', type_='unique')
    op.drop_index('ix_tribunal_sessions_status_proximo_retry', table_name='tribunal_sessions')
    op.drop_constraint(op.f('uq_tribunal_credentials_user_id_tribunal'), 'tribunal_credentials', type_='unique')
    op.drop_constraint(op.f('uq_movimentacoes_processo_id_data_movimentacao_descricao_hash'), 'movimentacoes', type_='unique')
    op.create_unique_constraint(op.f('uq_movimentacoes_processo_id_data_movimentacao_descricao'), 'movimentacoes', ['processo_id', 'data_movimentacao', 'descricao'], postgresql_nulls_not_distinct=False)
    op.drop_column('movimentacoes', 'descricao_hash')
    op.drop_constraint(op.f('uq_intimacoes_user_id_id_esaj'), 'intimacoes', type_='unique')
    op.create_unique_constraint(op.f('uq_intimacoes_id_esaj'), 'intimacoes', ['id_esaj'], postgresql_nulls_not_distinct=False)
    op.drop_constraint(op.f('uq_audiencias_user_id_id_esaj'), 'audiencias', type_='unique')
    op.create_unique_constraint(op.f('uq_audiencias_id_esaj'), 'audiencias', ['id_esaj'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
