"""torna cookie_encrypted nullable em tribunal_sessions

Revision ID: a46336bed1eb
Revises: f3d81e3a40ed
Create Date: 2026-08-13 23:52:22.291151

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'a46336bed1eb'
down_revision: Union[str, None] = 'f3d81e3a40ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tribunal_sessions', 'cookie_encrypted',
               existing_type=postgresql.BYTEA(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tribunal_sessions', 'cookie_encrypted',
               existing_type=postgresql.BYTEA(),
               nullable=False)
    # ### end Alembic commands ###
