"""adiciona cpf_mascarado em tribunal_credentials

Revision ID: f3d81e3a40ed
Revises: 38d4177c211b
Create Date: 2026-08-11 15:41:12.813887

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'f3d81e3a40ed'
down_revision: Union[str, None] = '38d4177c211b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tribunal_credentials', sa.Column('cpf_mascarado', sa.String(length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tribunal_credentials', 'cpf_mascarado')
    # ### end Alembic commands ###
