/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TarefasRouteImport } from './routes/tarefas'
import { Route as RedefinirSenhaRouteImport } from './routes/redefinir-senha'
import { Route as PushRobosRouteImport } from './routes/push-robos'
import { Route as PeticionamentoRouteImport } from './routes/peticionamento'
import { Route as PautasRouteImport } from './routes/pautas'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IntimacoesDiretasRouteImport } from './routes/intimacoes-diretas'
import { Route as GerenciasRouteImport } from './routes/gerencias'
import { Route as ElaboracoesRouteImport } from './routes/elaboracoes'
import { Route as DriveRouteImport } from './routes/drive'
import { Route as CustasDareRouteImport } from './routes/custas-dare'
import { Route as ConvitesRouteImport } from './routes/convites'
import { Route as ConsultaPastaRouteImport } from './routes/consulta-pasta'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OrganizacoesOrgIdRouteImport } from './routes/organizacoes.$orgId'
import { Route as ElaboracaoProcessoIdRouteImport } from './routes/elaboracao.$processoId'
import { Route as ConviteTokenRouteImport } from './routes/convite.$token'

const TarefasRoute = TarefasRouteImport.update({
  id: '/tarefas',
  path: '/tarefas',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/tarefas.lazy').then((d) => d.Route))
const RedefinirSenhaRoute = RedefinirSenhaRouteImport.update({
  id: '/redefinir-senha',
  path: '/redefinir-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const PushRobosRoute = PushRobosRouteImport.update({
  id: '/push-robos',
  path: '/push-robos',
  getParentRoute: () => rootRouteImport,
} as any)
const PeticionamentoRoute = PeticionamentoRouteImport.update({
  id: '/peticionamento',
  path: '/peticionamento',
  getParentRoute: () => rootRouteImport,
} as any)
const PautasRoute = PautasRouteImport.update({
  id: '/pautas',
  path: '/pautas',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IntimacoesDiretasRoute = IntimacoesDiretasRouteImport.update({
  id: '/intimacoes-diretas',
  path: '/intimacoes-diretas',
  getParentRoute: () => rootRouteImport,
} as any)
const GerenciasRoute = GerenciasRouteImport.update({
  id: '/gerencias',
  path: '/gerencias',
  getParentRoute: () => rootRouteImport,
} as any)
const ElaboracoesRoute = ElaboracoesRouteImport.update({
  id: '/elaboracoes',
  path: '/elaboracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const DriveRoute = DriveRouteImport.update({
  id: '/drive',
  path: '/drive',
  getParentRoute: () => rootRouteImport,
} as any)
const CustasDareRoute = CustasDareRouteImport.update({
  id: '/custas-dare',
  path: '/custas-dare',
  getParentRoute: () => rootRouteImport,
} as any)
const ConvitesRoute = ConvitesRouteImport.update({
  id: '/convites',
  path: '/convites',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/convites.lazy').then((d) => d.Route))
const ConsultaPastaRoute = ConsultaPastaRouteImport.update({
  id: '/consulta-pasta',
  path: '/consulta-pasta',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizacoesOrgIdRoute = OrganizacoesOrgIdRouteImport.update({
  id: '/organizacoes/$orgId',
  path: '/organizacoes/$orgId',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/organizacoes.$orgId.lazy').then((d) => d.Route),
)
const ElaboracaoProcessoIdRoute = ElaboracaoProcessoIdRouteImport.update({
  id: '/elaboracao/$processoId',
  path: '/elaboracao/$processoId',
  getParentRoute: () => rootRouteImport,
} as any)
const ConviteTokenRoute = ConviteTokenRouteImport.update({
  id: '/convite/$token',
  path: '/convite/$token',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/convite.$token.lazy').then((d) => d.Route),
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/consulta-pasta': typeof ConsultaPastaRoute
  '/convites': typeof ConvitesRoute
  '/custas-dare': typeof CustasDareRoute
  '/drive': typeof DriveRoute
  '/elaboracoes': typeof ElaboracoesRoute
  '/gerencias': typeof GerenciasRoute
  '/intimacoes-diretas': typeof IntimacoesDiretasRoute
  '/login': typeof LoginRoute
  '/pautas': typeof PautasRoute
  '/peticionamento': typeof PeticionamentoRoute
  '/push-robos': typeof PushRobosRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/tarefas': typeof TarefasRoute
  '/convite/$token': typeof ConviteTokenRoute
  '/elaboracao/$processoId': typeof ElaboracaoProcessoIdRoute
  '/organizacoes/$orgId': typeof OrganizacoesOrgIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/consulta-pasta': typeof ConsultaPastaRoute
  '/convites': typeof ConvitesRoute
  '/custas-dare': typeof CustasDareRoute
  '/drive': typeof DriveRoute
  '/elaboracoes': typeof ElaboracoesRoute
  '/gerencias': typeof GerenciasRoute
  '/intimacoes-diretas': typeof IntimacoesDiretasRoute
  '/login': typeof LoginRoute
  '/pautas': typeof PautasRoute
  '/peticionamento': typeof PeticionamentoRoute
  '/push-robos': typeof PushRobosRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/tarefas': typeof TarefasRoute
  '/convite/$token': typeof ConviteTokenRoute
  '/elaboracao/$processoId': typeof ElaboracaoProcessoIdRoute
  '/organizacoes/$orgId': typeof OrganizacoesOrgIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/consulta-pasta': typeof ConsultaPastaRoute
  '/convites': typeof ConvitesRoute
  '/custas-dare': typeof CustasDareRoute
  '/drive': typeof DriveRoute
  '/elaboracoes': typeof ElaboracoesRoute
  '/gerencias': typeof GerenciasRoute
  '/intimacoes-diretas': typeof IntimacoesDiretasRoute
  '/login': typeof LoginRoute
  '/pautas': typeof PautasRoute
  '/peticionamento': typeof PeticionamentoRoute
  '/push-robos': typeof PushRobosRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/tarefas': typeof TarefasRoute
  '/convite/$token': typeof ConviteTokenRoute
  '/elaboracao/$processoId': typeof ElaboracaoProcessoIdRoute
  '/organizacoes/$orgId': typeof OrganizacoesOrgIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/configuracoes'
    | '/consulta-pasta'
    | '/convites'
    | '/custas-dare'
    | '/drive'
    | '/elaboracoes'
    | '/gerencias'
    | '/intimacoes-diretas'
    | '/login'
    | '/pautas'
    | '/peticionamento'
    | '/push-robos'
    | '/redefinir-senha'
    | '/tarefas'
    | '/convite/$token'
    | '/elaboracao/$processoId'
    | '/organizacoes/$orgId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/configuracoes'
    | '/consulta-pasta'
    | '/convites'
    | '/custas-dare'
    | '/drive'
    | '/elaboracoes'
    | '/gerencias'
    | '/intimacoes-diretas'
    | '/login'
    | '/pautas'
    | '/peticionamento'
    | '/push-robos'
    | '/redefinir-senha'
    | '/tarefas'
    | '/convite/$token'
    | '/elaboracao/$processoId'
    | '/organizacoes/$orgId'
  id:
    | '__root__'
    | '/'
    | '/configuracoes'
    | '/consulta-pasta'
    | '/convites'
    | '/custas-dare'
    | '/drive'
    | '/elaboracoes'
    | '/gerencias'
    | '/intimacoes-diretas'
    | '/login'
    | '/pautas'
    | '/peticionamento'
    | '/push-robos'
    | '/redefinir-senha'
    | '/tarefas'
    | '/convite/$token'
    | '/elaboracao/$processoId'
    | '/organizacoes/$orgId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  ConsultaPastaRoute: typeof ConsultaPastaRoute
  ConvitesRoute: typeof ConvitesRoute
  CustasDareRoute: typeof CustasDareRoute
  DriveRoute: typeof DriveRoute
  ElaboracoesRoute: typeof ElaboracoesRoute
  GerenciasRoute: typeof GerenciasRoute
  IntimacoesDiretasRoute: typeof IntimacoesDiretasRoute
  LoginRoute: typeof LoginRoute
  PautasRoute: typeof PautasRoute
  PeticionamentoRoute: typeof PeticionamentoRoute
  PushRobosRoute: typeof PushRobosRoute
  RedefinirSenhaRoute: typeof RedefinirSenhaRoute
  TarefasRoute: typeof TarefasRoute
  ConviteTokenRoute: typeof ConviteTokenRoute
  ElaboracaoProcessoIdRoute: typeof ElaboracaoProcessoIdRoute
  OrganizacoesOrgIdRoute: typeof OrganizacoesOrgIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tarefas': {
      id: '/tarefas'
      path: '/tarefas'
      fullPath: '/tarefas'
      preLoaderRoute: typeof TarefasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redefinir-senha': {
      id: '/redefinir-senha'
      path: '/redefinir-senha'
      fullPath: '/redefinir-senha'
      preLoaderRoute: typeof RedefinirSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/push-robos': {
      id: '/push-robos'
      path: '/push-robos'
      fullPath: '/push-robos'
      preLoaderRoute: typeof PushRobosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/peticionamento': {
      id: '/peticionamento'
      path: '/peticionamento'
      fullPath: '/peticionamento'
      preLoaderRoute: typeof PeticionamentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pautas': {
      id: '/pautas'
      path: '/pautas'
      fullPath: '/pautas'
      preLoaderRoute: typeof PautasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intimacoes-diretas': {
      id: '/intimacoes-diretas'
      path: '/intimacoes-diretas'
      fullPath: '/intimacoes-diretas'
      preLoaderRoute: typeof IntimacoesDiretasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gerencias': {
      id: '/gerencias'
      path: '/gerencias'
      fullPath: '/gerencias'
      preLoaderRoute: typeof GerenciasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/elaboracoes': {
      id: '/elaboracoes'
      path: '/elaboracoes'
      fullPath: '/elaboracoes'
      preLoaderRoute: typeof ElaboracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drive': {
      id: '/drive'
      path: '/drive'
      fullPath: '/drive'
      preLoaderRoute: typeof DriveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/custas-dare': {
      id: '/custas-dare'
      path: '/custas-dare'
      fullPath: '/custas-dare'
      preLoaderRoute: typeof CustasDareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/convites': {
      id: '/convites'
      path: '/convites'
      fullPath: '/convites'
      preLoaderRoute: typeof ConvitesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consulta-pasta': {
      id: '/consulta-pasta'
      path: '/consulta-pasta'
      fullPath: '/consulta-pasta'
      preLoaderRoute: typeof ConsultaPastaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizacoes/$orgId': {
      id: '/organizacoes/$orgId'
      path: '/organizacoes/$orgId'
      fullPath: '/organizacoes/$orgId'
      preLoaderRoute: typeof OrganizacoesOrgIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/elaboracao/$processoId': {
      id: '/elaboracao/$processoId'
      path: '/elaboracao/$processoId'
      fullPath: '/elaboracao/$processoId'
      preLoaderRoute: typeof ElaboracaoProcessoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/convite/$token': {
      id: '/convite/$token'
      path: '/convite/$token'
      fullPath: '/convite/$token'
      preLoaderRoute: typeof ConviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  ConsultaPastaRoute: ConsultaPastaRoute,
  ConvitesRoute: ConvitesRoute,
  CustasDareRoute: CustasDareRoute,
  DriveRoute: DriveRoute,
  ElaboracoesRoute: ElaboracoesRoute,
  GerenciasRoute: GerenciasRoute,
  IntimacoesDiretasRoute: IntimacoesDiretasRoute,
  LoginRoute: LoginRoute,
  PautasRoute: PautasRoute,
  PeticionamentoRoute: PeticionamentoRoute,
  PushRobosRoute: PushRobosRoute,
  RedefinirSenhaRoute: RedefinirSenhaRoute,
  TarefasRoute: TarefasRoute,
  ConviteTokenRoute: ConviteTokenRoute,
  ElaboracaoProcessoIdRoute: ElaboracaoProcessoIdRoute,
  OrganizacoesOrgIdRoute: OrganizacoesOrgIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
