import type { AudienciaPainel } from '#/features/processos/processos.types'

/** Só entra na UI se a API de audiências vier vazia — aviso visível na página. */
export const PAUTAS_MOCK: AudienciaPainel[] = [
  {
    id: 'mock-pauta-1',
    processo_id: null,
    nu_processo: '1002561-84.2026.8.26.0100',
    tribunal: 'esaj_tjsp',
    titulo: 'Conciliação / Mediação (CEJUSC)',
    data_audiencia: '2026-06-18T17:00:00.000Z',
    local: '12ª Vara da Fazenda Pública - Comarca de São Paulo / Capital',
    situacao: null,
    parte_ativa: { nome: 'Acme Industrial Brasil S.A.', representada: true },
    parte_passiva: { nome: 'DETRAN/SP', representada: false },
    foro: 'Foro Central Cível',
    vara: '12ª Vara da Fazenda Pública',
    juiz: 'Dr. Rodrigo Amaral',
    fonte: 'agenda',
  },
  {
    id: 'mock-pauta-2',
    processo_id: null,
    nu_processo: '5001429-12.2026.4.03.6100',
    tribunal: 'pje_trf3',
    titulo: 'Instrução e Julgamento',
    data_audiencia: '2026-07-22T13:30:00.000Z',
    local: '1ª Vara Federal Previdenciária - São Paulo',
    situacao: null,
    parte_ativa: { nome: 'Carlos Eduardo da Silva Prado', representada: false },
    parte_passiva: { nome: 'INSS', representada: true },
    foro: 'Subseção Judiciária de São Paulo',
    vara: '1ª Vara Federal Previdenciária',
    juiz: 'Dra. Raquel Fernandes Mortani',
    fonte: 'agenda',
  },
  {
    id: 'mock-pauta-3',
    processo_id: null,
    nu_processo: '2004812-33.2026.8.26.0000',
    tribunal: 'esaj_tjsp',
    titulo: 'Julgamento Virtual',
    data_audiencia: '2026-08-28T16:30:00.000Z',
    local: '21ª Câmara de Direito Privado - TJSP',
    situacao: null,
    parte_ativa: { nome: 'Logística Express Transportes Ltda.', representada: true },
    parte_passiva: { nome: 'Banco Santander Brasil', representada: true },
    foro: 'Tribunal de Justiça de SP',
    vara: '21ª Câmara de Direito Privado',
    juiz: 'Des. Décio Rodrigues (Relator)',
    fonte: 'agenda',
  },
]
